version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo no pre-build.....yet 
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/java-demo-0.1.0.jar
    - README.md
cache:
  paths:
    - '/root/.m2/**/*'
